import Head from 'next/head'
import Blogs from '../components/blogs/blogs'
import Categories from '../components/categories/categories'

export default function Home() {
  return (
    <div className="sm:container mx-auto">
      <Head>
        <title>My Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Categories/>
      <Blogs/>
    </div>
  )
}
