import Head from "next//head"
import Blogss from "../../components/blogs/blogs"
import Categories from "../../components/categories/categories"
import { dataDummy } from "../../data_dummy/data_dummy"

const Blogs = () => {
    return (
        <div className="sm:container mx-auto">
            <Head>
                <title>My Blogs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Categories/>
            <Blogss data={dataDummy}/>
        </div>
    )
}

export default Blogs
